# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/saimanojappalla/Desktop/QgisUdemy/PyQT5/ui/geoserver-rest.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DlgMain(object):
    def setupUi(self, DlgMain):
        DlgMain.setObjectName("DlgMain")
        DlgMain.resize(625, 370)
        self.horizontalLayoutWidget = QtWidgets.QWidget(DlgMain)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 341))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.geoserverAuthGbx = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.geoserverAuthGbx.setObjectName("geoserverAuthGbx")
        self.label = QtWidgets.QLabel(self.geoserverAuthGbx)
        self.label.setGeometry(QtCore.QRect(10, 40, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.geoserverAuthGbx)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.geoserverAuthGbx)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_3.setObjectName("label_3")
        self.geoserverUrl = QtWidgets.QLineEdit(self.geoserverAuthGbx)
        self.geoserverUrl.setGeometry(QtCore.QRect(90, 40, 191, 21))
        self.geoserverUrl.setObjectName("geoserverUrl")
        self.geoserverUsername = QtWidgets.QLineEdit(self.geoserverAuthGbx)
        self.geoserverUsername.setGeometry(QtCore.QRect(90, 70, 191, 21))
        self.geoserverUsername.setObjectName("geoserverUsername")
        self.geoserverPassword = QtWidgets.QLineEdit(self.geoserverAuthGbx)
        self.geoserverPassword.setGeometry(QtCore.QRect(90, 100, 191, 21))
        self.geoserverPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.geoserverPassword.setObjectName("geoserverPassword")
        self.workspaceGbx = QtWidgets.QGroupBox(self.geoserverAuthGbx)
        self.workspaceGbx.setEnabled(False)
        self.workspaceGbx.setGeometry(QtCore.QRect(10, 190, 271, 131))
        self.workspaceGbx.setFocusPolicy(QtCore.Qt.NoFocus)
        self.workspaceGbx.setFlat(False)
        self.workspaceGbx.setCheckable(False)
        self.workspaceGbx.setChecked(False)
        self.workspaceGbx.setObjectName("workspaceGbx")
        self.workspaceName = QtWidgets.QLineEdit(self.workspaceGbx)
        self.workspaceName.setGeometry(QtCore.QRect(30, 50, 191, 21))
        self.workspaceName.setAlignment(QtCore.Qt.AlignCenter)
        self.workspaceName.setObjectName("workspaceName")
        self.createWorkspaceBtn = QtWidgets.QPushButton(self.workspaceGbx)
        self.createWorkspaceBtn.setGeometry(QtCore.QRect(70, 90, 113, 32))
        self.createWorkspaceBtn.setObjectName("createWorkspaceBtn")
        self.authenticateGeoserverBtn = QtWidgets.QPushButton(self.geoserverAuthGbx)
        self.authenticateGeoserverBtn.setGeometry(QtCore.QRect(80, 140, 113, 32))
        self.authenticateGeoserverBtn.setObjectName("authenticateGeoserverBtn")
        self.horizontalLayout.addWidget(self.geoserverAuthGbx)
        self.geoserverPublishGbx = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.geoserverPublishGbx.setEnabled(False)
        self.geoserverPublishGbx.setCheckable(False)
        self.geoserverPublishGbx.setChecked(False)
        self.geoserverPublishGbx.setObjectName("geoserverPublishGbx")
        self.label_4 = QtWidgets.QLabel(self.geoserverPublishGbx)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 191, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.geoserverPublishGbx)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_5.setObjectName("label_5")
        self.workspaceNameCreatedBefore = QtWidgets.QLineEdit(self.geoserverPublishGbx)
        self.workspaceNameCreatedBefore.setGeometry(QtCore.QRect(130, 60, 141, 21))
        self.workspaceNameCreatedBefore.setObjectName("workspaceNameCreatedBefore")
        self.storeName = QtWidgets.QLineEdit(self.geoserverPublishGbx)
        self.storeName.setGeometry(QtCore.QRect(130, 100, 141, 21))
        self.storeName.setObjectName("storeName")
        self.label_6 = QtWidgets.QLabel(self.geoserverPublishGbx)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_6.setObjectName("label_6")
        self.publishBtn = QtWidgets.QPushButton(self.geoserverPublishGbx)
        self.publishBtn.setGeometry(QtCore.QRect(70, 250, 113, 32))
        self.publishBtn.setObjectName("publishBtn")
        self.shapefilePath = QtWidgets.QLineEdit(self.geoserverPublishGbx)
        self.shapefilePath.setGeometry(QtCore.QRect(20, 210, 211, 31))
        self.shapefilePath.setObjectName("shapefilePath")
        self.openShapefileBtn = QtWidgets.QPushButton(self.geoserverPublishGbx)
        self.openShapefileBtn.setGeometry(QtCore.QRect(240, 210, 41, 32))
        self.openShapefileBtn.setObjectName("openShapefileBtn")
        self.horizontalLayout.addWidget(self.geoserverPublishGbx)

        self.retranslateUi(DlgMain)
        QtCore.QMetaObject.connectSlotsByName(DlgMain)

    def retranslateUi(self, DlgMain):
        _translate = QtCore.QCoreApplication.translate
        DlgMain.setWindowTitle(_translate("DlgMain", "Geoserver REST Plugin"))
        self.geoserverAuthGbx.setTitle(_translate("DlgMain", "Geoserver Authentication"))
        self.label.setText(_translate("DlgMain", "url:"))
        self.label_2.setText(_translate("DlgMain", "username:"))
        self.label_3.setText(_translate("DlgMain", "password:"))
        self.workspaceGbx.setTitle(_translate("DlgMain", "Create a Workspace in Geoserver"))
        self.workspaceName.setPlaceholderText(_translate("DlgMain", "Enter the name of workspace"))
        self.createWorkspaceBtn.setText(_translate("DlgMain", "Create"))
        self.authenticateGeoserverBtn.setText(_translate("DlgMain", "Authenticate"))
        self.geoserverPublishGbx.setTitle(_translate("DlgMain", "Publish Shapefile Geoserver"))
        self.label_4.setText(_translate("DlgMain", "Input shapefile to be published:"))
        self.label_5.setText(_translate("DlgMain", "Workspace name:"))
        self.label_6.setText(_translate("DlgMain", "Store name:"))
        self.publishBtn.setText(_translate("DlgMain", "Publish"))
        self.openShapefileBtn.setText(_translate("DlgMain", "..."))

